from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('farmacia/', views.farmacia, name='farmacia'),
    path('farmacia/busqueda/', views.farmacia_busqueda, name='farmacia_busqueda'),
    path('farmacia/entrega_insumos/', views.farmacia_entrega_insumos, name='farmacia_entrega_insumos'),
    path('asistencia/', views.asistencia, name='asistencia'),
    path('ayuda/', views.ayuda, name='ayuda'),
    path('configuracion/', views.configuracion, name='configuracion'),
    path('aportar/', views.aportar, name='aportar'),
    path('ingresos/', views.ingresos, name='ingresos'),
    path('reportes/', views.reportes, name='reportes'),
    path('registro_aportadores/', views.registro_aportadores, name='registro_aportadores'),
    path('index2/', views.index2, name='index2'),
    path('residentes/', views.residentes, name='residentes'),
    path('residentes/agregar/', views.agregar_residente, name='agregar_residente'),
    path('residentes/editar/<int:id>/', views.editar_residente, name='editar_residente'),
    path('residentes/eliminar/<int:id>/', views.eliminar_residente, name='eliminar_residente'),
    path('login_aportadores/', views.login_aportadores, name='login_aportadores'),
    path('login_colaboradores/', views.login_colaboradores, name='login_colaboradores'),
    path('validar_rut/', views.validar_rut, name='validar_rut'),
    path('validar_email/', views.validar_email, name='validar_email'),
    path('logout/', views.logout_view, name='logout'),
    path('mis_aportes/', views.mis_aportes, name='mis_aportes'),
    path('home/', views.home, name='home'),
    path('index/', views.index, name='index'),
    path('index/', views.index2, name='index'),
    path('agregar_residente/', views.agregar_residente, name='agregar_residente'),
    path('editar_residente/<int:residente_id>/', views.editar_residente, name='editar_residente'),
    path('farmacia/registrar-recepcion/', views.farmacia_registrar_recepcion, name='farmacia_registrar_recepcion'),
    path('farmacia/inventario/', views.farmacia_inventario, name='farmacia_inventario'),
]
