# Generated by Django 5.0.6 on 2024-07-01 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_residente_estado_salud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aportador',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='aportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aporte',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
