# Generated by Django 5.0.6 on 2024-07-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_aportador_is_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='estado_salud',
            field=models.CharField(default='Saludable', max_length=100),
        ),
        migrations.AddField(
            model_name='residente',
            name='fecha_ingreso',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
